# Generated by Django 6.0.4 on 2026-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='callanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='callanalysis',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='callanalysis',
            name='talk_ratio',
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='coaching_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='deal_stage_assessment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='missed_opportunities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='recommended_manager_action',
            field=models.CharField(choices=[('no_action', 'No Action'), ('review_with_rep', 'Review With Rep'), ('flag_for_pipeline_review', 'Flag for Pipeline Review')], default='no_action', max_length=50),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='skill_gaps',
            field=models.JSONField(default=list),
        ),
    ]
