# Generated by Django 6.0.4 on 2026-05-01 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_analysisjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
