# Generated by Django 6.0.4 on 2026-05-01 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_callanalysis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status'], name='calls_analy_status_bc8b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['created_at'], name='calls_analy_created_e0d41c_idx'),
        ),
    ]
