# Generated by Django 6.0.4 on 2026-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_callanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
