# Generated by Django 6.0.4 on 2026-05-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_analysisjob_updated_at_callanalysis_updated_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='analysis_jo_status_9da85d_idx',
            old_name='calls_analy_status_bc8b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='analysis_jo_created_996e67_idx',
            old_name='calls_analy_created_e0d41c_idx',
        ),
        migrations.AlterModelTable(
            name='analysisjob',
            table='analysis_job',
        ),
        migrations.AlterModelTable(
            name='call',
            table='call',
        ),
        migrations.AlterModelTable(
            name='callanalysis',
            table='call_analysis',
        ),
    ]
